"""
Declaration: Copyright (c), by idovelemoen, 2018. All right reserved.
Author: idovelemon[1322600812@qq.com]
Date: 2018-06-21
Brief: All config paramters
"""

# Core
ENTITY_CORE_ROTATE_SPEED = 1.0

# Core Rot
ENTITY_CORE_ROT_ROTATE_ACCEL = 0.1
ENTITY_CORE_ROT_ROTATE_DECEL = 0.1
ENTITY_CORE_ROT_ROTATE_MIN_SPEED = 1
ENTITY_CORE_ROT_ROTATE_MAX_SPEED = 10.0

# Normal Emitter
ENTITY_NORMAL_EMITTER_ROTATE_ACCEL = 0.1
ENTITY_NORMAL_EMITTER_ROTATE_DECEL = 0.1
ENTITY_NORMAL_EMITTER_ROTATE_MIN_SPEED = 1
ENTITY_NORMAL_EMITTER_ROTATE_MAX_SPEED = 10.0