"""
Declaration: Copyright (c), by idovelemoen, 2018. All right reserved.
Author: idovelemon[1322600812@qq.com]
Date: 2018-06-21
Brief: All config paramters
"""
# Core Dummy
ENTITY_CORE_DUMMY_MOVE_SPEED = 0.2

# Core
ENTITY_CORE_ROTATE_SPEED = 1.0

# Core Rot
ENTITY_CORE_ROT_ROTATE_ACCEL = 0.1
ENTITY_CORE_ROT_ROTATE_DECEL = 0.1
ENTITY_CORE_ROT_ROTATE_MIN_SPEED = 1
ENTITY_CORE_ROT_ROTATE_MAX_SPEED = 11.0

# Normal Emitter
NORMAL_EMITTER_SHOOT_DELTA = 5.0

# Normal Bullet
ENTITY_NORMAL_BULLET_MOVE_SPEED = 0.75

# Enemy 01
ENTITY_ENEMY_01_MOVE_SPEED = 0.28
ENTITY_ENEMY_01_ROTATE_SPEED = 30.0

# Enemy 02
ENTITY_ENEMY_02_IDLE_TIME = 30.0
ENTITY_ENEMY_02_RUSH_TIME = 60.0
ENTITY_ENEMY_02_RUSH_SPEED = 0.78